general {
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# Monitor Off after 5 minutes (300 seconds)
listener {
    timeout = 300
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# # Suspend after 2 hours (7200 seconds)
# listener {
#     timeout = 10
#     on-timeout = systemctl suspend
# }

# Suspend after 2 hours (7200 seconds)
#
listener {
    timeout = 7200
    on-timeout = hyprctl dispatch exec systemctl suspend
}
