[general]
font-sans = "Cascadia Mono NF"
font-mono = "Cascadia Mono NF"

[bar]
button-icon-size = 0.75
button-rounding = "full"
dropdown-opacity = 100

[modules.dashboard]
border-color = "transparent"

[modules.hyprland-workspaces]
display-mode = "icon"
active-indicator = "underline"
occupied-color = "bg-selected"
